# Generated by Django 4.2.4 on 2023-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20230904_0114'),
    ]

    operations = [
    ]
