# Generated by Django 4.2.4 on 2023-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_adress_address_rename_adress_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
